services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ${APP_NAME:-go-gin-clean-starter}-app
    volumes:
      - .:/app
    ports:
      - ${GOLANG_PORT:-8888}:8888
    networks:
      - app-network

  postgres:
    hostname: postgres
    container_name: ${APP_NAME:-go-gin-clean-starter}-db
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/postgresql/tmp:/var/lib/postgresql/data
      - app-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network

  redis:
      image: redis
      container_name: redis-server
      ports:
        - ${REDIS_PORT:-6379}:6379
      networks:
        - app-network

volumes:
  app-data:

networks:
  app-network:
    driver: bridge
